---
# tasks file for drupal

- name: installer composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755

- name: executer composer installer
  command: >
    php composer-installer.php
    chdir=/tmp
    creates=/usr/local/bin/composer
 
- name: depalcer composer dans un repertoire accessible
  shell: >
    mv /tmp/composer.phar /usr/local/bin/composer
    creates=/usr/local/bin/composer
  

- name: check out drush 8.x branch
  git:
    repo: https://github.com/drush-ops/drush.git
    version: 8.x
    dest: /opt/drush

- name: install drush dependances
  shell: >
    /usr/local/bin/composer install
    chdir=/opt/drush
    creates=/opt/drush/vendor/autoload.php
- name: create drush bin symlink
  file:
    src: /opt/drush/drush
    dest: /usr/local/bin/drush
    state: link


- name: check out drupal core tothe apache docroot
  git:
    repo: http://git.drupal.org/project/drupal.git
    version: "{{ drupal_core_version }}"
    dest: "{{ drupal_core_path }}"
- name: install drupal avec ses dependances
  shell: >
    /usr/local/bin/composer install
    chdir={{ drupal_core_path }}
    creates={{ drupal_core_path }}/vendor/autoload.php
- name: install drupal
  command: >
    drush si -y --site-name={{ drupal_site_name }}
    creates={{ drupal_core_path }}/sites/default/settings.php
  
- name: set permissions properly on settings.php
  file:
    path: "{{ drupal_core_path }}/sites/default/settings.php"
    mode: 0744
- name: set permissions on files dirctory
  file:
    path: "{{ drupal_core_path }}/sites/default/files"
    mode: 0777
    state: directory
    recurse: yes


